apiVersion: sinker.mkm.pub/v1alpha1
kind: ResourceSync
metadata:
  name: demo
  namespace: default
spec:
  source:
    resourceRef:
      apiVersion: v1
      kind: ConfigMap
      name: kube-root-ca.crt
    cluster:
      namespace: default
      kubeConfig:
        secretRef:
          name: k3-test-27-kubeconfig
          key: value
  destination:
    resourceRef:
      apiVersion: v1
      kind: ConfigMap
      name: demo
