apiVersion: sinker.influxdata.io/v1alpha1
kind: ResourceSync
metadata:
  name: demo
  namespace: default
spec:
  source:
    resourceRef:
      apiVersion: v1
      kind: ConfigMap
      name: remote-demo
    cluster:
      namespace: default
      kubeConfig:
        secretRef:
          name: k3-test-27-kubeconfig
          key: value
  target:
    resourceRef:
      apiVersion: v1
      kind: ConfigMap
      name: demo
  mappings:
    - fromFieldPath: data.remote
      toFieldPath: data.remote
    - fromFieldPath: data.foo
      toFieldPath: data.bar
