apiVersion: sinker.mkm.pub/v1alpha1
kind: ResourceSync
metadata:
  name: demo
  namespace: default
spec:
  source:
    resourceRef:
      kind: ConfigMap
      name: demo
      namespace: default
    cluster:
      kubeConfig:
        secretRef:
          name: k3-test-27-kubeconfig
          key: value
  destination:
    resourceRef:
      kind: ConfigMap
      name: demo
      namespace: default
